Update main_hungryfoxes.yml

diff --git a/.github/workflows/main_hungryfoxes.yml b/.github/workflows/main_hungryfoxes.yml
--- a/.github/workflows/main_hungryfoxes.yml
+++ b/.github/workflows/main_hungryfoxes.yml
@@ -26,7 +26,7 @@ jobs:
       - name: npm install, build, and test
         run: |
           npm install
-          npm run build --if-present
+          npm run build || (echo "Build failed!" && exit 1)
       - name: List files (debug)
         run: ls -la
 
